# Generated by Django 3.2.9 on 2021-11-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.IntegerField(blank=True, max_length=50, null=True)),
                ('refferal_by', models.CharField(blank=True, max_length=5, null=True)),
                ('refferal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=6, null=True)),
                ('token', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
