# Generated by Django 3.2.9 on 2021-11-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0002_auto_20211127_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='phoneno',
        ),
    ]
