# Generated by Django 3.2.9 on 2021-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0003_rename_email_userprofile_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
