# Generated by Django 3.2.9 on 2021-11-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0004_alter_userprofile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='refferal_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reffer_by',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
