# Generated by Django 3.2.9 on 2021-11-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0005_auto_20211127_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
