# Generated by Django 3.2.9 on 2021-11-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0006_userprofile_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.IntegerField(blank=True, null=True, unique=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
    ]
