# Generated by Django 3.2.9 on 2021-11-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0007_auto_20211127_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reffer_by',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
