# Generated by Django 3.2.9 on 2021-11-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0008_auto_20211128_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserValidate',
        ),
    ]
