# Generated by Django 3.2.9 on 2021-12-01 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resturent', '0011_auto_20211129_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('descrption', models.CharField(blank=True, max_length=250, null=True)),
                ('postimage', models.ImageField(blank=True, null=True, upload_to='post')),
                ('like', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
