# Generated by Django 3.2.9 on 2021-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0013_auto_20211201_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user'), ('vendor', 'vendor')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
