# Generated by Django 3.2.9 on 2021-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0018_alter_feed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower',
            field=models.IntegerField(default=0),
        ),
    ]
