# Generated by Django 3.2.9 on 2021-12-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0020_auto_20211209_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('cricket', 'cricket'), ('football', 'user'), ('vollyball', 'volyball'), ('kabadi', 'kabadi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user'), ('player', 'player')], max_length=20, null=True),
        ),
    ]
